### PR TITLE
Update to API 7

### PR DESCRIPTION
**Pull request by pie-flavor**

### CODE REVIEW

**Comment by simon816** [comment]
Thanks for this!
Surprised how few changes are actually needed.

I've been thinking of rewriting some of the permissions interface, so some of that would probably not be needed.
I'll merge this when I next work on Chat UI.

**Comment by pie-flavor** [comment]
I'm not super happy with https://github.com/simon816/ChatUI/pull/7/commits/1877cb40e7e1140e4c38e8ed1674f21575d115c3#diff-8462ed02a63fe8d3a3b13e3a6b35b344R291 and https://github.com/simon816/ChatUI/pull/7/commits/1877cb40e7e1140e4c38e8ed1674f21575d115c3#diff-8462ed02a63fe8d3a3b13e3a6b35b344R284 , by the way. I don't quite know how to make the whole thing async, but adding .get() on a Future just seems wrong.

**Comment by simon816** [comment]
I would say calling `get()` isn't inherently wrong; that's how you wait on an async result to complete.
What I would do is keep the signature of `createOption` and `removeOption` and do the `get()` call in there, makes the lambda look nicer.
I may look into providing better support for async, if there's no easy way of doing it currently.

**Comment by pie-flavor** [comment]
I'm changing the target branch so I can keep doing stuff to my fork. Continued in #8

**Pull request closed without merging**
